### ISSUE TITLE
fatal error: 'Flurry+Event.h' file not found

### ISSUE THREAD

**Issue by Talgat777** [flurry/flutter-flurry-sdk#1]
Hi,

I'm getting this error when I try to run the app on IOS simulator from Flutter:

Command CompileSwiftSources failed with a nonzero exit code
.../flutter_sdk/.pub-cache/git/flutter-flurry-sdk-d785749ebbc8f4d368e200d8126c036bec0ddb0e/ios/Classes/FlurryFlutterPlugin.m:5:9: fatal error: 'Flurry+Event.h' file not found
    #import "Flurry+Event.h"
            ^~~~~~~~~~~~~~~~
    1 error generated.

**Comment by FlurryDevNP** [comment]
Hi @Talgat777 , is this issue still there or has it been resolved?

**Comment by Talgat777** [comment]
Hi @FlurryDevNP! 

We've fixed this issue but then hit another one, going to create a new issue!
