### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by tHEO2k17** [flurry/flutter-flurry-sdk#10]
Error output from Xcode build:
↳
    2022-04-11 13:17:36.645 xcodebuild[36344:337962] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-04-11 13:17:36.646 xcodebuild[36344:337962] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/s1/9h8v5bk16_qbjgr_1l5xhbnc0000gn/T/flutter_tools.JY8GTb/flutter_ios_build_temp_dircuezVA/temporary_xcresult_bundle

    /Users/theo/.pub-cache/hosted/pub.dartlang.org/flutter_flurry_sdk-2.0.0/ios/Classes/FlurryFlutterPlugin.m:5:9: fatal error: 'Flurry+Event.h' file not found
    #import "Flurry+Event.h"
            ^~~~~~~~~~~~~~~~
    1 error generated.
    Command CompileSwiftSources failed with a nonzero exit code
    Command CompileSwiftSources failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
    	/var/folders/s1/9h8v5bk16_qbjgr_1l5xhbnc0000gn/T/flutter_tools.JY8GTb/flutter_ios_build_temp_dircuezVA/temporary_xcresult_bundle

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Lexical or Preprocessor Issue (Xcode): 'Flurry+Event.h' file not found
/Users/theo/.pub-cache/hosted/pub.dartlang.org/flutter_flurry_sdk-2.0.0/ios/Classes/FlurryFlutterPlugin.m:4:8

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).

**Comment by hantao-flurrydev** [comment]
@tHEO2k17 could you provide us with how you build the project? Without further information, We couldn't recognize the issue. Also did you run `flutter pub get` first? If so, cold you try run `flutter clean` to see if that helps

**Comment by Phelickz** [comment]
I got the same error also when building iOS

**Comment by hantao-flurrydev** [comment]
Hi @Phelickz, thanks for reporting this issue. We recently released 12.0.0 for native iOS SDK, and looks like the flutter plugin integrated the latest native iOS sdk since we don't specify the version in `.podspec` file. We will release a patch shortly to fix the missing arm64 issue in native sdk, and will update you once release is done.

**Comment by poting-oath** [comment]
Fix released at flutter_flurry_sdk 2.2.0.

**Comment by poting-oath** [comment]
@tHEO2k17 @Phelickz More fix released at flutter_flurry_sdk 2.2.1.

**Comment by Phelickz** [comment]
@poting-oath 
Thanks for letting me know. I’ll check it out
