### ISSUE TITLE
Flurry stops building after updates to other

### ISSUE THREAD

**Issue by jodymac** [flurry/flutter-flurry-sdk#11]
Flurry version is unchanged, but will no longer build.

To recreate, create a new project and only add flurry as a dependency.  Originally I discovered the problem with my other app that flurry was working fine in until I did updates.  I'm building in flutter for ios simulator.

---------------------------------------------- mac terminal output
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/5p/5lvh9h8s3fz7ljqzbpy0_8th0000gn/T/flutter_tools.oRah3U/flutt
    	er_ios_build_temp_dirkUoZ6N/temporary_xcresult_bundle

    /Users/jody/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_flurr
    y_sdk-2.0.0/ios/Classes/FlurryFlutterPlugin.m:428:39: warning: implicit
    conversion loses integer precision: 'NSInteger' (aka 'long') to 'int'
    [-Wshorten-64-to-32]
        [Flurry setSessionContinueSeconds:secondsInt];
        ~                                 ^~~~~~~~~~
    1 warning generated.
    1 warning generated.
    ld: warning: ignoring file
    /Users/jody/Desktop/Flutter-Projects/flurry_test/build/ios/Debug-iphonesimul
    ator/Flurry-iOS-SDK/Flurry_iOS_SDK.framework/Flurry_iOS_SDK, missing
    required architecture arm64 in file
    /Users/jody/Desktop/Flutter-Projects/flurry_test/build/ios/Debug-iphonesimul
    ator/Flurry-iOS-SDK/Flurry_iOS_SDK.framework/Flurry_iOS_SDK (2 slices)
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_FlurryParamBuilder", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_FlurryCCPA", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_FlurryUserProperties", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_Flurry", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
         (maybe you meant: _OBJC_CLASS_$_FlurryFlutterPlugin)
      "_OBJC_CLASS_$_FlurrySessionBuilder", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_FConfig", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_FlurryMessaging", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see
    invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/jody/Desktop/Flutter-Projects/flurry_test/ios/Pods/Pods.xcodeproj:
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is
    set to 8.0, but the range of supported deployment target versions is 9.0 to
    15.2.99. (in target 'Flurry-iOS-SDK' from project 'Pods')

    Result bundle written to path:
    	/var/folders/5p/5lvh9h8s3fz7ljqzbpy0_8th0000gn/T/flutter_tools.oRah3U/flutt
    	er_ios_build_temp_dirkUoZ6N/temporary_xcresult_bundle

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlurryParamBuilder

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlurryCCPA

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlurryUserProperties

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_Flurry

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlurrySessionBuilder

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FConfig

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlurryMessaging

Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.

-------------------------------- flutter doctor
✓] Flutter (Channel stable, 2.10.4, on macOS 11.6.3 20G415 darwin-x64, locale
    en-US)
    • Flutter version 2.10.4 at /Users/jody/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jody/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

**Comment by hantao-flurrydev** [comment]
Hi @jodymac, thanks for reporting this issue. We recently released 12.0.0 for native iOS SDK, and looks like the flutter plugin integrated the latest native iOS sdk since we don't specify the version in `.podspec` file. We will release a patch shortly to fix the missing arm64 issue in native sdk, and will update you once release is done.

**Comment by jodymac** [comment]
Terrific!  I've had to release several updates with Flurry disabled and look forward to getting it back in there!

**Comment by jodymac** [comment]
Saw the plugin was updated about 7 hours ago.  Gave it a try.  New error that prevents building is...

[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/jody/Desktop/Flutter-Projects/niks/ios/Pods/Flurry-iOS-SDK/CrashReporter.xcframework)

**Comment by SalsabeelaHasan** [comment]
@jodymac I face this issue also when using the latest update.

**Comment by hantao-flurrydev** [comment]
Hi @jodymac, @SalsabeelaHasan, this is possibly because of how our native sdk was packaged in the recent releases (we released our xcframework based on static library which has crash reporter xcframework based on .framework as a dependency). We have many reporters from cocoapods and other plugins about the similar issues, and we are about to release our native sdk with new build structure to fix such issues in one week or two. So please stay tuned.

**Comment by hantao-flurrydev** [comment]
@SalsabeelaHasan @jodymac you might want to remove `use_frameworks!` as a temporary fix for building the project.

**Comment by jodymac** [comment]
I had tried that before.  It doesn't work in my case.  My project blows up even with flurry removed and disabling use_frameworks!.

**Comment by jodymac** [comment]
Not to be a complainer as I do appreciate the package, but these bugs are taking an extraordinarily long time to fix.  I have been unable to use this package for 2 months, 1/6 of a whole year.   I get that maybe the flutter community might be small compared to others, but I believe that's simply due to brand recognition on this platform.  I had used Flurry years ago when I was an ios only developer and was excited to find this package, but now I'm wondering if I can risk using the package.  I don't want to have to gut my application from flurry calls and remove from pubspec.yaml every time there is an issue.  I get that issues will occur and  I could experience the necessity to wait on using an updated flutter for a short time.  But not 1/6 of a year and counting.

**Comment by poting-oath** [comment]
Fix released at flutter_flurry_sdk 2.2.0.

**Comment by jodymac** [comment]
Unfortunately there are still issues.
I ran multiple pod updates, pod install, flutter cleans all with the same result.
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/jody/Desktop/Flutter-Projects/niks/ios/Pods/Flurry-iOS-SDK/CrashReporter.xcframework, /Users/jody/Desktop/Flutter-Projects/niks/ios/Pods/Flurry-iOS-SDK/Flurry_Config.xcframework, /Users/jody/Desktop/Flutter-Projects/niks/ios/Pods/Flurry-iOS-SDK/Flurry_Messaging.xcframework, and /Users/jody/Desktop/Flutter-Projects/niks/ios/Pods/Flurry-iOS-SDK/Flurry_iOS_SDK.xcframework)

    • Flutter version 3.0.4 at /Users/jody/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (11 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

**Comment by jodymac** [comment]
Flurry 2.2.1 lets my app build and run now.

**Comment by poting-oath** [comment]
@jodymac Thanks for the info and your feedback!
