### ISSUE TITLE
How to get the push token?

### ISSUE THREAD

**Issue by dev-yakuza** [flurry/flutter-flurry-sdk#15]
To send the test push notification, the push token is required.

![Screen Shot 2022-07-16 at 10 36 15](https://user-images.githubusercontent.com/42969906/179329745-b240445b-5651-4c17-8d73-aba21baf0f83.jpg)

But, I don't know how to get the push token.

How to get the push token?

**Comment by poting-oath** [comment]
@dev-yakuza You can add a messaging listener in your app to get the token. Please see `lib/messaging.dart` section in https://pub.dev/packages/flutter_flurry_sdk#example. The whole example with this feature can also be found in https://pub.dev/packages/flutter_flurry_sdk/example.

```
...
  @override
  void onTokenRefresh(String token) {
    print('Flurry Messaging Type: onTokenRefresh'
        '\n    Token: $token');
  }
```

**Comment by poting-oath** [comment]
@dev-yakuza Another easier way to "Send test push message" from the Flurry web UI is to select "Advertising ID" instead of "Push Token". The Ad ID is very easy to find from your test device.

**Comment by dev-yakuza** [comment]
> @dev-yakuza You can add a messaging listener in your app to get the token. Please see `lib/messaging.dart` section in https://pub.dev/packages/flutter_flurry_sdk#example. The whole example with this feature can also be found in https://pub.dev/packages/flutter_flurry_sdk/example.
> 
> ```
> ...
>   @override
>   void onTokenRefresh(String token) {
>     print('Flurry Messaging Type: onTokenRefresh'
>         '\n    Token: $token');
>   }
> ```

@poting-oath Thanks for your info. I tried the code, but I couldn't get the token at the first time... Maybe, I miss something.

So, I try it again and let you know the result.

**Comment by dev-yakuza** [comment]
@poting-oath 

on Android, I got the log in Debug console like the following

```
I/FlurryAgent( 5337): Firebase token received: XXXX
```

And when I use the example code, I got the log like the following.

```
I/flutter ( 5337): Flurry Messaging Type: onTokenRefresh
I/flutter ( 5337):     Token: XXXXXX
```

So, I can get the toke from it. Thanks! 🙇 

However, there is no log on iOS. How to get the token on iOS? Is it the same code working well on iOS? 🤔

**Comment by flurrydev** [comment]
@dev-yakuza 

On iOS you should see a line in the debug console like this: 
`"fl.notification.key" : "c6780cbe5afbac25df738ebcb061d09ec39854314e17635f1849c634dd8e9131`

It will only show up for a real iphone (not simulator).

Make sure you have the `.withMessaging(true)` in your Flurry builder.

And have your capabilities enabled: 
<img width="868" alt="Screen Shot 2022-07-19 at 2 58 22 PM" src="https://user-images.githubusercontent.com/4580734/179827988-418e053b-4fad-4d2a-8bd3-05554fb9c021.png">

**Comment by poting-oath** [comment]
@dev-yakuza FYI, for iOS, the Flutter Messaging listener can only receive, `onNotificationReceived` & `onNotificationClicked`, but NOT `onNotificationCancelled` & `onTokenRefresh`.

**Comment by dev-yakuza** [comment]
@poting-oath 

Thanks for your info!

I can get the token on Android and iOS. And, I can send a test message.

I close this issue.

Thanks again and have a nice day 🙇
