### ISSUE TITLE
support m1 mac simulator

### ISSUE THREAD

**Issue by pontus-jeong** [flurry/flutter-flurry-sdk#17]
if run **flutter-flurry-sdk** pub with m1 mac simulator, show this error
``` shell
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FlurryFlutterPlugin
```
but run **flutter-flurry-sdk** pub with real phone(iPhone 12 Pro), it doesn't happen.

**Comment by poting-oath** [comment]
@mero-jung I can run simulator on M1 Mac without any issue! Did you copy your project directly from you non-M1 Mac? Please try to clean all previous build/cache and retry.

**Comment by pontus-jeong** [comment]
when run app show error like
```
Error (Xcode): Framework not found Pods_Runner

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
```

i clean cache

flutter clean > pod deintegrate > remove Podfile.lock & pubspec.lock > flutter pub get > pod install

if remove flutter_flurry_sdk, not show error and run correctly.

**Comment by pontus-jeong** [comment]
I don't no why, suddenly run conrrectly. while flutter run -v

so close this issue...

**Comment by poting-oath** [comment]
Yes, looks like it was an old cache issue. Sometimes you need to run few times to rebuild the project.
