### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by Talgat777** [flurry/flutter-flurry-sdk#4]
Can't compile sdk for Android:

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:
- package:flutter_flurry_sdk

The library 'package:flutter_flurry_sdk/flurry.dart' is legacy, and should not be imported into a null safe library.

**Comment by Talgat777** [comment]
Oh, seems to be the duplicate of the existing issue https://github.com/flurry/flutter-flurry-sdk/issues/2

Closing this issue then

**Comment by poting-oath** [comment]
@Talgat777 
Null Safety is now supported https://pub.dev/packages/flutter_flurry_sdk
Please use `$ flutter pub add flutter_flurry_sdk` to install in your projects.

Thanks for your supports!
