### ISSUE TITLE
Flurry.builder error in Flutter Application

### ISSUE THREAD

**Issue by iamsaurabhc** [flurry/flutter-flurry-sdk#5]
After updating my pubspec.yaml file with

```
flutter_flurry_sdk:
    git:
     url: https://github.com/flurry/flutter-flurry-sdk.git
```
and running `flutter pub update`, getting an error while initializing Flurry Builder [in main.dart] with following code 

```
Flurry.builder
    .withCrashReporting(true)
    .withLogEnabled(true)
    .withLogLevel(LogLevel.debug)
    .build(
        androidAPIKey: API_KEY,
            iosAPIKey: API_KEY);
```

**ERROR: Functions must have an explicit list of parameters. Try adding a parameter list.**

Please HELP!

**Comment by poting-oath** [comment]
@iamsaurabhc Cannot reproduce it.

Looks like your codes define some functions or constructors without the parameters. (e.g., `MyMethod` instead of `MyMethod()`). You should be able to see where the error is from the build logs.

FYI, now `flutter-flurry-sdk` is released on the official `pub.dev` site (https://pub.dev/packages/flutter_flurry_sdk). You can install it by the command  `$ flutter pub add flutter_flurry_sdk`.

**Comment by iamsaurabhc** [comment]
@poting-oath Thanks for the quick reply!
Rechecked all the files, all looks correct. Only the error popping up in Flurry.builder.

![Screenshot from 2022-02-08 12-22-24](https://user-images.githubusercontent.com/19235748/152934335-ebf481c0-51a2-4adf-901a-e61cf2020978.png)

PS: I tried installing with `$ flutter pub add flutter_flurry_sdk` still getting the same error even though flurry SDK is definitely installed already.

**Comment by poting-oath** [comment]
@iamsaurabhc This initialization is statement that needs to be run inside a function or constructor. For example,
```
lass MyAppState extends State<MyApp> {
  static const String FLURRY_ANDROID_API_KEY = 'YOUR_ANDROID_API_KEY';
  static const String FLURRY_IOS_API_KEY     = 'YOUR___IOS___API_KEY';

  @override
  void initState() {
    super.initState();

    Flurry.builder
        .withCrashReporting(true)
        .withLogEnabled(true)
        .withLogLevel(LogLevel.debug)
        .build(
            androidAPIKey: FLURRY_ANDROID_API_KEY,
                iosAPIKey: FLURRY_IOS_API_KEY);
  }
...
}
```

**Comment by iamsaurabhc** [comment]
Thanks! This solved the error. @poting-oath do you think documentation update is required for this?
