### ISSUE TITLE
Flurry.logStandardEvent

### ISSUE THREAD

**Issue by KennyChan94P** [flurry/flutter-flurry-sdk#9]
I managed to get "EventRecordStatus.eventRecorded" with the code below 
```
var paramBuilder = Param()
                .putBooleanParam(EventParam.success, true)
                .putStringParam(EventParam.userId, '${_user!.id}')
                .putString(
                    'note', '${_user!.fullName} logged in successfully.');
            EventRecordStatus res =
                await Flurry.logStandardEvent(FlurryEvent.login, paramBuilder);
            print("Flurry.logStandardEvent res: $res");
```

but i still do not manage to see the event being triggered in the Event Details Dashboard as shown below
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/62973895/158302510-f1fd8930-57b7-47b8-89f8-eb852d11ae39.png">

may i know what am i missing?

thank you.

**Comment by poting-oath** [comment]
@KennyChan94P Your codes look correct!
Flurry will send out the events after your apps end or background for more than 10 sec. And usually Flurry server will show the data few hours delay.
Do you see the event counts now?

**Comment by poting-oath** [comment]
@KennyChan94P FYI, Flurry had outages around March 10-11, if that's the cause of your issue.

**Comment by KennyChan94P** [comment]
@poting-oath hi, thank you for your reply and yes i do see the event counts now! thank you so much.
